## Neural Network Demo

In [2]:
%load_ext autoreload
%autoreload 2
#See bmes.ahmet/README.TXT for setting up BMESAHMETDIR environment variable.
import sys,os; sys.path.append(os.environ['BMESAHMETDIR']); import bmes

import pandas as pd
import numpy as np
import sklearn
from pylab import *

## Simple Classification Example

In [7]:
XT=np.array([[0,0,0],[1,0,1],[0,1,1],[1,1,0], [0,0,0],[1,0,1],[0,1,1],[1,1,0]]);
X=XT[:,:-1]; T=XT[:,-1];
print(XT)

[[0 0 0]
 [1 0 1]
 [0 1 1]
 [1 1 0]
 [0 0 0]
 [1 0 1]
 [0 1 1]
 [1 1 0]]


In [15]:
# Use MLPClassifier for classification and MLPRegressor for regression.
from sklearn.neural_network import MLPClassifier

# Create the network, set its parameters, train and predict:
# e.g., with 1 hidden unit:
mlp = MLPClassifier(hidden_layer_sizes=(1,), activation='logistic')
mlp.fit(X,T)
Y = mlp.predict(X)
print(Y)

[1 1 1 1 1 1 1 1]


In [16]:
# you can let the mlp do the accuracy calculation:
print('Accuracy: ' + str( mlp.score(X,T) ) )

# For classification problems, additional performance metrics (precision, recall) available from:
from sklearn.metrics import classification_report
print(classification_report(T,Y))

Accuracy: 0.5
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         4
           1       0.50      1.00      0.67         4

    accuracy                           0.50         8
   macro avg       0.25      0.50      0.33         8
weighted avg       0.25      0.50      0.33         8



c:\ProgramData\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\ProgramData\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\ProgramData\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Neural Network Regression

In [3]:
#% house_dataset contains
#% information about 506 real estate properties, and their relative valuation (in the last column).
housefile = bmes.downloadurl('https://sacan.biomed.drexel.edu/lib/exe/fetch.php?rev=&media=course:ml:nn:nndemo:house_dataset.csv','house_dataset.csv');

import pandas
t = pandas.read_csv(housefile,header=None);
X=t.iloc[:,:-1].to_numpy()
T=t.iloc[:,-1].to_numpy()
X.shape, T.shape

((506, 13), (506,))

In [4]:
## Prepare Training & Test Sets.
# I am generating Training & Test sets for only 1 of the folds. In your applications, you would need to run for all folds.

# For k-fold separation (e.g., k=4):
# For classification problems, use StratifiedKFold; for regression problems use KFold.
from sklearn.model_selection import KFold

kf = KFold(n_splits=4)
Itrain,Itest = next(kf.split(X,T)) #and obtain the first training & test set
Xtrain = X[Itrain,:]
Ttrain = T[Itrain]
Xtest = X[Itest, :]
Ttest = T[Itest]
#...

# to use skf in a for loop, you can use:
# for Itrain, Itest in skf.split(X,T):
#   ...

In [12]:
# Use MLPClassifier for classification and MLPRegressor for regression.
from sklearn.neural_network import MLPRegressor

# Create the network, set its parameters, train and predict:
# e.g., with 1 hidden unit:
mlp = MLPRegressor(hidden_layer_sizes=(1,), activation='identity')
mlp.fit(Xtrain,Ttrain)

Ytest = mlp.predict(Xtest)
print(np.stack((Ytest[0:5],Ttest[0:5]),axis=1) ) #just printing the first few predictions...

[[ 1.74170829 24.        ]
 [14.38899218 21.6       ]
 [ 3.49192581 34.7       ]
 [ 0.39394965 33.4       ]
 [ 5.61135048 36.2       ]]


/home/muaddib/.conda/envs/bmes547/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:684: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [17]:
# you can let the mlp do the score calculation:
print('Test set R^2 (proportion of variance) score: ' + str( mlp.score(Xtest,Ttest) ) )

# or calculate R^2 yourself:
from sklearn.metrics import r2_score
r2_score(Ttest,Ytest)

Test set R^2 (proportion of variance) score: -18.794118619500324


-18.794118619500324